import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Güven Ağı",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className={"antialiased"}>
        <div>{auth}</div>
        {children}
      </body>
    </html>
  );
}
